name: Install Solana and Anchor
description: Installs Solana and Anchor

inputs:
  solana_version: # id of input
    description: "The Solana version to install, e.g. 1.9.0"
    required: true
    default: ${{ env.SOLANA_VERSION }}
  solana_package:
    description: "The Solana package to use."
    required: true
    default: solana-basic

runs:
  # Install Cachix
  - uses: cachix/install-nix-action@v16
    with:
      install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
      install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
  - name: Setup Cachix
    uses: cachix/cachix-action@v10
    with:
      name: saber

  # Install Solana
  - name: Install Linux dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y pkg-config build-essential libudev-dev

  - name: Cache Solana binaries
    id: solana-cache
    uses: actions/cache@v2
    with:
      path: |
        ~/.cache/solana
        ~/.local/share/solana/install
      key: ${{ runner.os }}-${{ inputs.solana_version }}
  - name: Install Solana
    if: steps.solana-cache.outputs.cache-hit != 'true'
    run: |
      nix shell 'git://github.com/saber-hq/saber-overlay#${{ inputs.solana_package }}' --command solana-install init ${{ inputs.solana_version }}
  - name: Setup Solana Path
    run: |
      echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
      solana --version
